version: '3.9'

services:
  devops-service-1:
    build: .
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=my_super_secure_jwt_key

  devops-service-2:
    build: .
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=my_super_secure_jwt_key

  kong:
    image: kong:3.4
    container_name: kong
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
    volumes:
      - ./deploy/kong.yml:/usr/local/kong/declarative/kong.yml
    depends_on:
      - devops-service-1
      - devops-service-2